version: 1.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:ap-south-1:860061945305:task-definition/suvabose-eureka-server:1"
        LoadBalancerInfo:
          ContainerName: "eureka-server"
          ContainerPort: "80"
        PlatformVersion: "LATEST"
