version: 1.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:ap-south-1:860061945305:task-definition/pension-detail:latest"
        LoadBalancerInfo: "pension-details-suva"
          ContainerName: "suvabose-pension-management-system-registry"
          ContainerPort: "8083"
        PlatformVersion: "LATEST"
