version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
      java: corretto11
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region $AWS_REGION)
  build:
    commands:
      - echo Build started on `date`
      - echo Building java
      - mvn clean package
      - echo Building the docker image
      - docker build -t suvabose-pension-management-system-registry::latest .
      - docker tag pensioner-detail-service 860061945305.dkr.ecr.ap-south-1.amazonaws.com/suvabose-pension-management-system-registry:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - docker push 860061945305.dkr.ecr.ap-south-1.amazonaws.com/suvabose-pension-management-system-registry:latest
      - echo Writing definition files
      - printf '[{"name":"suvabose-pension-management-system-registry","imageUri":"%s"}]' 860061945305.dkr.ecr.ap-south-1.amazonaws.com/suvabose-pension-management-system-registry:latest > imagedefinitions

artifacts:
  files: pensioner-detail-service/imagedefinitions.json
